CREATE TABLE TEST(
    ID NUMBER(4),
    NAME VARCHAR2(3));
    
DESC TEST;

--한글은 글자 하나당 2Byte로 처리 
INSERT INTO TEST VALUES(1000,'홍길동');
--영어는 글자 하나당 1BYTE로 처리
INSERT INTO TEST VALUES(1000,'ABC');

-- 언어마다 서로 다른 BYTE 처리를 보완하기 위해 NCHAR,NVARCHAR2


--NCHAR,NVARCHAR2 차이 : 고정된 길이를 항상 가지고 있느냐 아니냐의 차이
--NCHAR 경우에는 글자가 1만 입력이 되도 4자리를 유지
CREATE TABLE TEST2(
    ID NCHAR(4),
    NAME NVARCHAR2(3)); --바이트숫자가아니라 문자개수
    
INSERT INTO TEST2 VALUES('황보강성','홍길동');

CREATE  TABLE TEST3(
    ID NVARCHAR2(4),
    NAME NVARCHAR2(4),
    REG_DATE DATE);
    
INSERT INTO TEST3 VALUES('황보강성','홍길동',SYSDATE);
INSERT INTO TEST3 VALUES('황보강성','홍길동','2020-11-09');

--테이블 생성하기
--CREATE TABLE 테이블명( 열이름 타입,.......);
--CREATE TABLE 테이블명 AS SELECT * FROM EMP;
--CREATE TABLE 테이블명 AS SELECT * FROM EMP WHERE DEPTNO=20;
--CREATE TABLE 테이블명 AS SELECT * FROM EMP WHERE 1<>1;

DESC EMP;

CREATE TABLE EMP_DDL(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),--전체 자릿수는 7자리 (소수점 2자리를 포함할수있음)
    COMM NUMBER(7,2), --12345.78
    DEPTNO NUMBER(2));
    
-- ALTER : 수정(테이블변경)
--컬럼 추가 
ALTER TABLE EMP_DDL ADD HP VARCHAR2(20);

--기존 컬럼명 변경
ALTER TABLE EMP_DDL RENAME COLUMN HP TO TEL;

--기존 타입 변경
ALTER TABLE EMP_DDL MODIFY EMPNO NUMBER(5);

--기존 컬럼 삭제
ALTER TABLE EMP_DDL DROP COLUMN TEL;

--테이블 명 변경
RENAME EMP_DDL TO EMP_RENAME;



DESC EMP_RENAME;

--멤버 테이블만들기

CREATE TABLE MEMBER(
    ID CHAR(8),
    NAME NVARCHAR2(10),
    ADDR NVARCHAR2(50),
    NATION NCHAR(4),
    EMAIL VARCHAR2(50),
    AGE NUMBER(7,2));
    
DESC MEMBER;

--실습2 테이블변경
ALTER TABLE MEMBER ADD BIGO NVARCHAR2(20);

ALTER TABLE MEMBER MODIFY BIGO NVARCHAR2(30);

ALTER TABLE MEMBER RENAME COLUMN BIGO TO REMARK;   

DROP TABLE MEMBER;
    