--회원가입, 게시글 등록, 입금...

--기존의 dept 테이블을 복사해서 dept_temp 테이블 생성
CREATE TABLE DEPT_TEMP AS SELECT * FROM DEPT;
--테이블을 새로운곳에 만들어냄 

--현재 테이블 조회 
SELECT*
FROM DEPT_TEMP;


--데이터 추가하기 (방법1)
INSERT INTO DEPT_TEMP(DEPTNO,DNAME,LOC)
VALUES(50,'DATABASE','SEOUL');

--데이터 추가하기 (방법2)
INSERT INTO DEPT_TEMP VALUES(60,'NETWORK','BUSAN');

--필드명 줄것이냐 안줄것이냐 //주지않는다면 순서를 꼭 지켜야함

INSERT INTO DEPT_TEMP(DEPTNO,DNAME,LOC)
VALUES(50,'DATABASE'); --세개 넣을거야 하고 위에써놓고 밸류에 2개밖에 안적었기때문에 에러발생

INSERT INTO DEPT_TEMP(DEPTNO,DNAME,LOC)
VALUES(500,'DATABASE','SEOUL'); --두자리만입력하기로되어있는 DEPTNO에서 3자리가 되니 에러

--NULL 삽입하기
--명시적으로 NULL 삽입
INSERT INTO DEPT_TEMP(DEPTNO,DNAME,LOC)
VALUES(70,'DATABASE',NULL);

INSERT INTO DEPT_TEMP(DEPTNO,DNAME,LOC)
VALUES(80,'MOBALE','');


--묵시적으로 NULL 삽입
INSERT INTO DEPT_TEMP(DEPTNO,LOC)
VALUES(90,'INCHEON');

--EMP테이블을 복사하여 EMP_TEMP 테이블 생성
CREATE TABLE EMP_TEMP AS SELECT*FROM EMP;


--테이블 삭제
DROP TABLE EMP_TEMP;

--EMP테이블을 복사하여 EMP_TEMP 테이블 생성하되 구조만 복사하기
CREATE TABLE EMP_TEMP AS SELECT*FROM EMP WHERE 1<>1;
SELECT*FROM EMP_TEMP;

DESC EMP_TEMP;
INSERT INTO EMP_TEMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES(9999,'홍길동','PRESIDENT',NULL,'2020/11/09',4000,NULL,10);
INSERT INTO EMP_TEMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES(8888,'성춘향','MANAGER',NULL,'2020/10/08',3000,NULL,10);

--최종반영
COMMIT;

INSERT INTO EMP_TEMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES(7777,'유승호','MANAGER',NULL,TO_DATE('07/01/2010','DD/MM/YYYY'),4000,NULL,20);

INSERT INTO EMP_TEMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES(6666,'이순신','MANAGER',NULL,SYSDATE,4000,NULL,20);

--EMP 테이블에서 SALGRADE 테이블을 참조하여 급여 등급이 1등급인 사원만을
--EMP_TEMP 테이블에 추가하고 싶다면?
--서브쿼리로 작성하기(데이터가 추가되는 테이블의 열 개수와 서브ㅝ리의 열 개수가 일치)
INSERT INTO EMP_TEMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
SELECT EMPNO,ENAME,JOB,MGR,HIREDATe,SAL,COMM,DEPTNO
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND S.GRADE = 1;

COMMIT;